-- =========================================
-- DormN Database Schema
-- =========================================


-- 1. users
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    kakao_id TEXT NOT NULL UNIQUE,

    room_number VARCHAR(20) UNIQUE,

    dorm_verified BOOLEAN NOT NULL DEFAULT FALSE,

    dorm_verified_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- 2. posts
CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    author_id BIGINT NOT NULL
        REFERENCES users(id)
        ON DELETE RESTRICT,

    product_name VARCHAR(200) NOT NULL,

    product_url TEXT,

    image_url TEXT,

    total_price INTEGER NOT NULL
        CHECK (total_price > 0),

    total_quantity INTEGER NOT NULL
        CHECK (total_quantity > 0),

    host_quantity INTEGER NOT NULL
        CHECK (host_quantity >= 1),

    deadline TIMESTAMPTZ NOT NULL,

    pickup_location VARCHAR(200) NOT NULL,

    shortfall_policy VARCHAR(30) NOT NULL
        CHECK (
            shortfall_policy IN (
                'KEEP_BY_HOST',
                'CANCEL_IF_SHORT'
            )
        ),

    status VARCHAR(30) NOT NULL DEFAULT 'RECRUITING'
        CHECK (
            status IN (
                'RECRUITING',
                'CLOSED',
                'ORDERED',
                'ARRIVED',
                'PICKUP',
                'COMPLETED',
                'CANCELLED'
            )
        ),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CHECK (host_quantity <= total_quantity)
);


-- 3. participations
CREATE TABLE participations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    post_id BIGINT NOT NULL
        REFERENCES posts(id)
        ON DELETE CASCADE,

    user_id BIGINT NOT NULL
        REFERENCES users(id)
        ON DELETE RESTRICT,

    quantity INTEGER NOT NULL
        CHECK (quantity >= 1),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (post_id, user_id)
);


-- 4. settlements
CREATE TABLE settlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    participation_id BIGINT NOT NULL UNIQUE
        REFERENCES participations(id)
        ON DELETE CASCADE,

    amount INTEGER NOT NULL
        CHECK (amount >= 0),

    payment_status VARCHAR(20) NOT NULL DEFAULT 'UNPAID'
        CHECK (
            payment_status IN (
                'UNPAID',
                'SENT',
                'CONFIRMED'
            )
        ),

    sent_at TIMESTAMPTZ,

    confirmed_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);